### ISSUE TITLE
Clean up Error Log

### ISSUE THREAD

**Issue by Kalkstein** [Kalkstein/ww1#3]
### To **all** contributors:

Please keep the error log clean as this is the only way of producing good code and it makes life better for every other contributor. The goal is to reduce the upstream errors to zero. This would enable us to immediately see if an error occurs, if the log shows up. Reproduce that with `--debug` option passed as starting parameter.
It is a good amount of work, but has to be done either way - the more early, the more easy to go on.
Also check if you could get rid of warnings, as they usually show mistakes too.

**Comment by Eagle020** [comment]
I fixed all the history files, which caused many errors because of our new techs and the new countries from the sunflower patch.
Next step would be to fix all the state and province ID conflcits
